### ISSUE TITLE
ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by nikhiljohn10** [pawamoy/git-changelog#26]
**Describe the bug**
I am trying to create a changelog for [pi-clap](https://github.com/nikhiljohn10/pi-clap). But it is showing internal error regarding version. Is there a workaround for this?

**To Reproduce**
1. `pip3 install git-changelog==0.3.0`
2. `git-changelog -o CHANGELOG.md -t keepachangelog -s basic .`

**Output**
```
Traceback (most recent call last):
  File "/Users/nikzjon/Library/Python/3.7/bin/git-changelog", line 8, in <module>
    sys.exit(main())
  File "/Users/nikzjon/Library/Python/3.7/lib/python/site-packages/git_changelog/cli.py", line 90, in main
    changelog = Changelog(args.repository, style=args.style)
  File "/Users/nikzjon/Library/Python/3.7/lib/python/site-packages/git_changelog/build.py", line 206, in __init__
    planned_tag = bump(last_tag, "minor")
  File "/Users/nikzjon/Library/Python/3.7/lib/python/site-packages/git_changelog/build.py", line 12, in bump
    major, minor, patch = version.split(".", 2)
ValueError: not enough values to unpack (expected 3, got 2)
```

**System (please complete the following information):**
- `git-changelog` version: 0.3.0 ( same result in 0.4.0 )
- Python version: 3.7
- OS: MacOS 10.15.6

P.S. The documentation of the usage of this package is not enough.

**Comment by pawamoy** [comment]
Hello, thank you for the bug report! My first guess is that your git tag does not follow the [semver specification](https://semver.org/). The code expects three parts separated by dots and it seems there are only two. We could consider adding support for generic tags though I'm not sure what would be the impact at first glance. We will have to think this through. I should have some time in september to think about it :slightly_smiling_face: 

About the docs, yes, it's true, it could be better :sweat_smile:

**Comment by nikhiljohn10** [comment]
> 
> 
> Hello, thank you for the bug report! My first guess is that your git tag does not follow the [semver specification](https://semver.org/). The code expects three parts separated by dots and it seems there are only two. We could consider adding support for generic tags though I'm not sure what would be the impact at first glance. We will have to think this through. I should have some time in september to think about it 🙂
> 
> About the docs, yes, it's true, it could be better. 😅 I'll see what I can do in september.

@pawamoy Your guess is correct about version numbering. I used [PEP 440](https://www.python.org/dev/peps/pep-0440/) standards. Also my code use sphinx documentation. The conf.py defined as part of it have a 'version' and 'release' variable. In that, the format for version is X.Y and release is X.Y.ZrcN. For the code for version extraction and verification, check https://www.python.org/dev/peps/pep-0440/#appendix-b-parsing-version-strings-with-regular-expressions

**Comment by nikhiljohn10** [comment]
I just tested it with my code version == 1.2 & release == 1.2.1

But still getting same error output.

**Comment by nikhiljohn10** [comment]
I think this is not a bug at all when I debugged using code from this repo. In my `develop` branch, the tag string is empty. Hence the error. But tags are fine inside the `master` branch. I think I need to rework on my tagging method.

**Comment by pawamoy** [comment]
In any case, we could consider supporting more version numbering specifications, especially PEP440. Feel free to open a new issue if this is something you'd like. Thank you for coming back and closing the issue :slightly_smiling_face:
