### ISSUE TITLE
Broken links to gitlab

### ISSUE THREAD

**Issue by Yajo** [pawamoy/git-changelog#29]
**Describe the bug**
Reading the README, I found these broken links:

https://github.com/pawamoy/git-changelog/blob/036f96a7e34a8c13f4467e0c24502b51424cdf2a/README.md#L44-L46

... which happened to be just what I wanted to read 😭 

**Expected behavior**
Not broken 😄

**Comment by pawamoy** [comment]
Ah! Nice catch. The same issues exist on GitHub, I'll fix the links, thanks!

**Comment by pawamoy** [comment]
Should be fixed, thanks again!
