### ISSUE TITLE
Add support for Jinja2 version 3.x

### ISSUE THREAD

**Issue by Vanessa-Kris** [pawamoy/git-changelog#33]
Hello, I was trying to build the git-changelog for Fedora 35/36 and it was locked to Jinja2 < 3.x. Meanwhile, Fedora 35/36 uses Jinja2 == 3.x

**Comment by pawamoy** [comment]
Hi @Vanessa-Kris, thanks for the heads up, I'll update the dependency accepted range :slightly_smiling_face:

**Comment by pawamoy** [comment]
Just pushed version 0.5.0.
