### ISSUE TITLE
Calver

### ISSUE THREAD

**Issue by AXGKl** [pawamoy/git-changelog#34]
Hi Tim,

**Is your feature request related to a problem? Please describe.**

I had to upgrade git-changelog to 0.5.x, because of flask requiring Jinja 3, while older versions of git-changelog want <v3 for Jinja.

Now running git-changelog on some projects breaks, due to

https://github.com/pawamoy/git-changelog/commit/b68a565fce51f8d0e94f0f67c98dea30e421dd8f 

where you use the Semver lib instead of re to get version numbers.

Problem: The re based parsing worked well also for non semver, i.e. calver (e.g. 2022.03.01).
While the semver lib refuses to parse this into version number fractions.
EDIT: It actually works with "2022.3.1" but not with **zero padded month or day** - which I use for sort-ability.

I guess this is not a bug:
From your changelog I understand that you target exclusively semver based projects.
But well, I understood the semver part of the feature list up to now as an (optional) feature but not a hard requirement for projects. And it used to work well :-)

**Describe the solution you'd like**

I don't know your plans for git-changelog and if you intend to build more and more semver-exclusive feats in.
But maybe you'd like to consider supporting also calver at least to an extent like you had it up to your 0.5 version - for me it was perfectly working.

So possibly you could offer the version bumb function's algo as changeable on the CLI (e.g. `-c: calver based version support`) and if given, use the old re based parser?

EDIT: Seeing that "2022.1.3" *is* parsed by `semver` - maybe the most easy and robust approach would be, to just replace ".0" with "." in `build.py`'s `def bump` - you could still exclusively use the lib then, instead of `re`.

**Comment by pawamoy** [comment]
Sure, I definitely agree on supporting CalVer, and more generally PEP 440. Not all projects use SemVer.
I'd like to avoid hacks and rely on tested libraries. There are probably utilitiess in the Python standard library that allow to parse PEP 440 versions. PRs are welcome, not sure when I'll find time to work on this project :slightly_smiling_face:

**Comment by AXGKl** [comment]
Good to hear you are busy and not idling around :D 

I'll have a look if I can do it, when I find time, also  a bit loaded ;-)

**Comment by pawamoy** [comment]
We recently refactored the code to support multiple versioning schemes, so it's now possible to add support for CalVer.
