### ISSUE TITLE
Add gitlab commit convention

### ISSUE THREAD

**Issue by javathought** [pawamoy/git-changelog#36]
** gitlab convention for commit uses standard git trailers to type changes **

Changes for changelog are identified by the trailer Changelog: <type>
A dictionary is used to map the type code to the type label (more user friendly) used in the generated changelog

**solution desired**
- add a style option (-s / --style) for using git trailers
- add an option to specify a file mapping types of a change to "readable" labels 

**gitlab convention links**
https://docs.gitlab.com/ee/api/repositories.html#add-changelog-data-to-a-changelog-file

**Comment by pawamoy** [comment]
So, new version 1.0.0 supports parsing Git trailers, so I'll close this :slightly_smiling_face:
