### ISSUE TITLE
Feature: Chose a provider explicitly

### ISSUE THREAD

**Issue by TheoGoudout** [pawamoy/git-changelog#37]
**Is your feature request related to a problem? Please describe.**
When working on a repo hosted on a private Gitlab instance, provider detection is not working

**Describe the solution you'd like**
It would be nice to be able to specify explicitly that an instance is running on Gilab. That would solve the missing `compare` links.

**Describe alternatives you've considered**
The only alternative I can think of is adding these links manually.

**Comment by pawamoy** [comment]
Good suggestion. I remember having tried to do that elegantly before but failed / give up. Reviewing your PR now!

**Comment by sandzhaj** [comment]
@pawamoy actually #55 resolves that. I had the same problem, but specified provider in pyproject.toml
Works well
Maybe it's time to release new tag? :)

**Comment by pawamoy** [comment]
Done!
