### ISSUE TITLE
Feature: Specify next version explicitly

### ISSUE THREAD

**Issue by TheoGoudout** [pawamoy/git-changelog#38]
**Is your feature request related to a problem? Please describe.**
When generating the CHANGELOG of a version I'm about to commit, I need to rely on git-changelog to guess correctly what will be the next version.

**Describe the solution you'd like**
I would like to be able to specify explicitly the next version number I'm about to tag. Either that, or specify whether it's going to be a patch, minor or major version.

**Describe alternatives you've considered**
The alternative would be to commit the CHANGELOG in another commit, but I think I want to avoid that.

**Comment by pawamoy** [comment]
Goog suggestion as well, thanks!! I guess we could add a `--bump-to` CLI option with which you can pass the exact new version?

**Comment by TheoGoudout** [comment]
I'm wondering whether this extra parameter could conflict with existing options ? Namely `--bump`

**Comment by pawamoy** [comment]
I think there's a mistake in the docs, the current option name is `--bump-latest`. But yeah, obviously we must make sure the options do not conflict :slightly_smiling_face:
