### ISSUE TITLE
Include merge commits only

### ISSUE THREAD

**Issue by oesteban** [pawamoy/git-changelog#53]
**Is your feature request related to a problem? Please describe.**

Seems like a use case of #43, but perhaps an option for it would be particularly appreciated.

**Describe the solution you'd like**

A way of instructing git-changelog to generate the log with only merge commits, and extracting the commit message from the first line of the merge commit, following how the GHA Release Drafter and the new Release generator of GH work (interesting also to link the PR and the author of the PR).

**Describe alternatives you've considered**

Perhaps the include/exclude of #43 with sophisticated filtering options?

**Comment by pawamoy** [comment]
If you extract only the first line of the merge commit message, will it be enough to generate the changelog :thinking: 
I'm not sure to follow here. Could you share some examples to illustrate what you mean? Some fake git logs and the expected changelog?

**Comment by oesteban** [comment]
This might be an error on my side. I have recently checked, and it seems like git-changelog was doing exactly what I tried to explain above. I'll close it for now and reopen only if the feature request still makes sense after double-checking.
