### ISSUE TITLE
bug: error docs

### ISSUE THREAD

**Issue by FANGOD** [pawamoy/git-changelog#67]
>> git-changelog -c basic -t angular -v
usage: git-changelog [--config-file [PATH ...]] [-b] [-B VERSION] [-h] [-i] [-g VERSION_REGEX] [-m MARKER_LINE] [-o OUTPUT] [-p {github,gitlab,bitbucket}] [-r] [-R] [-I INPUT] [-c {angular,conventional,basic}] [-s SECTIONS] [-t {angular,keepachangelog}] [-T]
                     [-E] [-Z] [-F FILTER_COMMITS] [-V] [--debug-info]
                     [REPOSITORY]
git-changelog: error: unrecognized arguments: -v

**Comment by pawamoy** [comment]
Thanks for the report. That's a doc issue indeed (README not up-to-date). Will update it :slightly_smiling_face:

**Comment by pawamoy** [comment]
Docs fixed (and improved!)
