### ISSUE TITLE
bug: Commits are assigned to wrong version when using multiple release branches

### ISSUE THREAD

**Issue by chme** [pawamoy/git-changelog#70]
### Description of the bug

When using more than one branch to release versions __and__ if one release branch gets merged into another release branch, depending on when in time commits happen on the two branches, commits might get assigned (and listed in the generated changelog) to the wrong version.

Instead of only taking into account, when in time a commit and tag happened, I think, it is necessary to also check, that the commit is reachable from a tag/version.

@pawamoy: I drafted a solution at https://github.com/chme/git-changelog/tree/fix/assign-versions
But before polishing it, I wanted to check with you, if the way to solve it is OK, if there is something I am missing and if you would be OK with adding this kind of change.

### To Reproduce

For example given the following git commit graph, with `main` and `develop` branches:

```mermaid
    gitGraph
       commit id: "A" tag: "1.0"
       branch develop
       commit id: "X"
       commit id: "Y"
       checkout main
       commit id: "B"
       commit id: "C" tag: "1.1"
       checkout develop
       merge main
       commit id: "Z" tag: "2.0"
```

Git log will return the commits in the following order:

- A (tag: `1.0`)
- X
- Y
- B
- C (tag: `1.1`)
- Z (tag: `2.0`)

And therefor `git-changelog` will generate a changelog with:

- `2.0`
  - Z
- `1.1`
  - C
  - B
  - Y __this commit is only in `2.0`__
  - X __this commit is only in `2.0`__
- `1.0`
  - A 

### Expected behavior

The commits should be listed under a version that they belong to / are ancestors of.

For the above example, the expected changelog would look like:

- `2.0`
  - Z
  - Y
  - X
- `1.1`
  - C
  - B
- `1.0`
  - A 
 
### Environment information

```bash
git-changelog --debug-info  # | xclip -selection clipboard
```

- __System__: Linux-6.6.17-277.current-x86_64-with-glibc2.39
- __Python__: cpython 3.10.13
- __Environment variables__:
- __Installed packages__:
  - `git-changelog` v2.4.0

### Additional context

I have created a test repository, that shows a problematic git tree and the generated CHANGELOG.md at https://github.com/chme/gitchangelog-test
- [CHANGELOG.md](https://github.com/chme/gitchangelog-test/blob/main/CHANGELOG.md)
- [Git tree/Network graph](https://github.com/chme/gitchangelog-test/network)

**Comment by pawamoy** [comment]
Hi, omg yes, thanks a lot for working on this! It's definitely something I'd like to merge :) I can't review the changes in your fork right now but I'll let you know once I did :)

**Comment by chme** [comment]
That was quick 🙂

I'll fix the issues you mentioned and also add some first tests before opening the pull request.
