### ISSUE TITLE
Loss of ability to capture untyped section commits

### ISSUE THREAD

**Issue by autumnjolitz** [pawamoy/git-changelog#88]
Changeset https://github.com/pawamoy/git-changelog/commit/f191ed7c05029674e52c8ada55e0d9e861c320cc broke access to the untyped_sections by never adding commits with `{"type": ""}` to the sections list.

See https://github.com/pawamoy/git-changelog/blob/b9bad9c9093e4fe6436e7ed0cd88e2c4d4a0f6af/src/git_changelog/build.py#L162

The if statement will filter out commits that ordinarily would be assigned to the `""` section (e.g. "untyped_section")

Because of this change, it is now impossible to "catch" untyped commits and handle within the template (or anywhere else at all) unless one literally assigns commits not belonging to any section back to the untyped section manually.

**Comment by pawamoy** [comment]
Hi @autumnjolitz, thank you so much for the report, investigation and fix! Let me comment on the PR :slightly_smiling_face:
