### ISSUE TITLE
bug: GIT_CHANGELOG_REMOTE not working

### ISSUE THREAD

**Issue by TheExiledCat** [pawamoy/git-changelog#92]
### Description of the bug

When using an alias HostName for a remote (for example when having multiple ssh users in .ssh/config, the commit message hrefs in the output markdown are linking to that replacement hostname instead of the real host (e.g. github,com/repo)
However, following the documentation, settings the GIT_CHANGELOG_REMOTE value to an http or ssh link to the repo causes all the commit messages to instead look like this [hash]() with an empty link.
### To Reproduce

```
WRITE MRE / INSTRUCTIONS HERE
```

### Expected behavior

The commit messages correctly link to the actual replaced remote

### Environment information

```bash
git-changelog --debug-info  # | xclip -selection clipboard
```

- __System__: Linux-6.5.0-35-generic-x86_64-with-glibc2.35
- __Python__: cpython 3.10.12 (/usr/bin/python3)
- __Environment variables__:
- __Installed packages__:
  - `git-changelog` v2.5.2

**Comment by pawamoy** [comment]
Hi @TheExiledCat, thanks for the report.

The `GIT_CHANGELOG_REMOTE` value must be the name of a configured remote, not an HTTP(S) or SSH link. Does that solve your issue?

**Comment by TheExiledCat** [comment]
> Hi @TheExiledCat, thanks for the report.
> 
> The `GIT_CHANGELOG_REMOTE` value must be the name of a configured remote, not an HTTP(S) or SSH link. Does that solve your issue?

Forgive me if im missing something, does that mean i just have to configure some other remote, and make it the env variable? Eg. Origin2

**Comment by pawamoy** [comment]
Yes!

```bash
git remote add your-remote-name https://yoururl
GIT_CHANGELOG_REMOTE=your-remote-name
```

**Comment by TheExiledCat** [comment]
> Yes!
> 
> ```bash
> git remote add your-remote-name https://yoururl
> GIT_CHANGELOG_REMOTE=your-remote-name
> ```

Ah okay thank you, my bad haha.

**Comment by pawamoy** [comment]
No problem, glad I could help :slightly_smiling_face:
